#!/bin/bash

# Update and install required packages
yes | pkg install x11-repo
yes | pkg update
yes | pkg install proot-distro

# Install Ubuntu
yes | proot-distro install ubuntu

# Create a file to load the environment faster
echo "proot-distro login ubuntu" > ubuntu

# Make the file executable
chmod +x ubuntu

# Run the file
./ubuntu
