#!/bin/bash

# Update and install required packages
yes | pkg install x11-repo
yes | pkg update
yes | pkg install proot-distro

# Install Ubuntu
yes | proot-distro install debian

# Create a file to load the environment faster
echo "proot-distro login debian" > debian

# Make the file executable
chmod +x debian

# Run the file
./debian
