#!/bin/bash

# Set Username
read -r -p "Please enter desired username: " username </dev/tty

termux-setup-storage
termux-change-repo

# Update and install required packages
yes | pkg install x11-repo
yes | pkg update
yes | pkg uninstall dbus
yes | pkg install wget ncurses-utils dbus proot-distro x11-repo tur-repo pulseaudio git virglrenderer-android xfce4 xfce4-goodies pavucontrol-qt jq nala wmctrl firefox netcat-openbsd
yes | proot-distro install debian

# Setup proot
proot-distro login debian -- env DISPLAY=:1.0 apt update
proot-distro login debian -- env DISPLAY=:1.0 apt upgrade -y
proot-distro login debian -- env DISPLAY=:1.0 apt install sudo wget nala jq -y

#Create user
proot-distro login debian -- env DISPLAY=:1.0 groupadd storage
proot-distro login debian -- env DISPLAY=:1.0 groupadd wheel
proot-distro login debian -- env DISPLAY=:1.0 useradd -m -g users -G wheel,audio,video,storage -s /bin/bash "$username"

#Add user to sudoers
chmod u+rw $HOME/../usr/var/lib/proot-distro/installed-rootfs/debian/etc/sudoers
echo "$username ALL=(ALL) NOPASSWD:ALL" | tee -a $HOME/../usr/var/lib/proot-distro/installed-rootfs/debian/etc/sudoers > /dev/null
chmod u-w  $HOME/../usr/var/lib/proot-distro/installed-rootfs/debian/etc/sudoers

#Set proot DISPLAY
echo "export DISPLAY=:1.0" >> $HOME/../usr/var/lib/proot-distro/installed-rootfs/debian/home/$username/.bashrc

#Set proot aliases
echo "
alias virgl='GALLIUM_DRIVER=virpipe '
alias apt='sudo nala '
" >> $HOME/../usr/var/lib/proot-distro/installed-rootfs/debian/home/$username/.bashrc

#Set proot timezone
timezone=$(getprop persist.sys.timezone)
proot-distro login debian -- env DISPLAY=:1.0 rm /etc/localtime
proot-distro login debian  -- env DISPLAY=:1.0 cp /usr/share/zoneinfo/$timezone /etc/localtime

#Create .bashrc
cp $HOME/../usr/var/lib/proot-distro/installed-rootfs/debian/etc/skel/.bashrc $HOME/.bashrc

#Enable Sound
echo "
pulseaudio --start --exit-idle-time=-1
pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1
" > $HOME/.sound

echo "
source .sound" >> .bashrc

#Set aliases
echo "
alias debian='proot-distro login debian --user $username --shared-tmp'
alias apt='pkg upgrade -y && nala $@'
" >> $HOME/.bashrc

#Put Firefox icon on Desktop
cp $HOME/../usr/share/applications/firefox.desktop $HOME/Desktop 
chmod +x $HOME/Desktop/firefox.desktop

# Install Termux-X11
sed -i '12s/^#//' $HOME/.termux/termux.properties

wget https://github.com/phoenixbyrd/Termux_XFCE/raw/main/termux-x11.deb
dpkg -i termux-x11.deb
rm termux-x11.deb
apt-mark hold termux-x11-nightly

echo -e "#!/bin/bash\n\nMESA_NO_ERROR=1 MESA_GL_VERSION_OVERRIDE=4.3COMPAT MESA_GLES_VERSION_OVERRIDE=3.2 virgl_test_server_android --angle-gl & > /dev/null 2>&1\nsleep 1\nXDG_RUNTIME_DIR=\${TMPDIR} termux-x11 :1.0 &\nsleep 1\nam start --user 0 -n com.termux.x11/com.termux.x11.MainActivity > /dev/null 2>&1\nsleep 1\nenv DISPLAY=:1.0 GALLIUM_DRIVER=virpipe dbus-launch --exit-with-session xfce4-session & > /dev/null 2>&1\n\nsleep 5\nprocess_id=\$(ps -aux | grep '[x]fce4-screensaver' | awk '{print \$2}')\nkill \"\$process_id\" > /dev/null 2>&1" > start

chmod +x start

